version: "3.8"

services:
  web:
    build: .
    volumes:
      - ./app:/app
    environment:
      - FLASK_ENV=development
      - PYTHONPATH=/
      - FLASK_APP=main.py
    command: flask run --host=0.0.0.0 --port=5000
    networks:
      - internal

  worker:
    build: .
    volumes:
      - ./app:/app
    environment:
      - PYTHONPATH=/
    command: huey_consumer.py app.tasks.huey
    networks:
      - internal

  redis:
    image: "redis:alpine"
    networks:
      - internal

networks:
  internal:
    driver: bridge
