version: '3.8'

services:
  testing_web:
    build: .
    ports:
      - "${WEB_PORT:-5000}:5000"
    volumes:
      - ./app:/app
    environment:
      - FLASK_ENV=development
      - PYTHONPATH=/
      - FLASK_APP=main.py
    command: flask run --host=0.0.0.0 --port=5000

  testing_worker:
    build: .
    volumes:
      - ./app:/app
    environment:
      - PYTHONPATH=/
    command: huey_consumer.py app.tasks.huey

  testing_redis:
    image: "redis:alpine"
